export const TEAMS = [
  { code: 'FWC', name: 'FIFA World Cup', count: 20 },
  { code: 'CC', name: 'Coca-Cola', count: 14 },
  { code: 'MEX', name: 'Mexico', count: 20 },
  { code: 'RSA', name: 'South Africa', count: 20 },
  { code: 'KOR', name: 'South Korea', count: 20 },
  { code: 'CZE', name: 'Czechia', count: 20 },
  { code: 'CAN', name: 'Canada', count: 20 },
  { code: 'BIH', name: 'Bosnia and Herzegovina', count: 20 },
  { code: 'QAT', name: 'Qatar', count: 20 },
  { code: 'SUI', name: 'Switzerland', count: 20 },
  { code: 'BRA', name: 'Brazil', count: 20 },
  { code: 'MAR', name: 'Morocco', count: 20 },
  { code: 'HAI', name: 'Haiti', count: 20 },
  { code: 'SCO', name: 'Scotland', count: 20 },
  { code: 'USA', name: 'USA', count: 20 },
  { code: 'PAR', name: 'Paraguay', count: 20 },
  { code: 'AUS', name: 'Australia', count: 20 },
  { code: 'TUR', name: 'Türkiye', count: 20 },
  { code: 'GER', name: 'Germany', count: 20 },
  { code: 'CUW', name: 'Curaçao', count: 20 },
  { code: 'CIV', name: 'Ivory Coast', count: 20 },
  { code: 'ECU', name: 'Ecuador', count: 20 },
  { code: 'NED', name: 'Netherlands', count: 20 },
  { code: 'JPN', name: 'Japan', count: 20 },
  { code: 'SWE', name: 'Sweden', count: 20 },
  { code: 'TUN', name: 'Tunisia', count: 20 },
  { code: 'BEL', name: 'Belgium', count: 20 },
  { code: 'EGY', name: 'Egypt', count: 20 },
  { code: 'IRN', name: 'Iran', count: 20 },
  { code: 'NZL', "name": "New Zealand", count: 20 },
  { code: 'ESP', name: 'Spain', count: 20 },
  { code: 'CPV', name: 'Cape Verde', count: 20 },
  { code: 'KSA', name: 'Saudi Arabia', count: 20 },
  { code: 'URU', name: 'Uruguay', count: 20 },
  { code: 'FRA', name: 'France', count: 20 },
  { code: 'SEN', name: 'Senegal', count: 20 },
  { code: 'IRQ', name: 'Iraq', count: 20 },
  { code: 'NOR', name: 'Norway', count: 20 },
  { code: 'ARG', name: 'Argentina', count: 20 },
  { code: 'ALG', name: 'Algeria', count: 20 },
  { code: 'AUT', name: 'Austria', count: 20 },
  { code: 'JOR', name: 'Jordan', count: 20 },
  { code: 'POR', name: 'Portugal', count: 20 },
  { code: 'COD', name: 'Congo DR', count: 20 },
  { code: 'UZB', name: 'Uzbekistan', count: 20 },
  { code: 'COL', name: 'Colombia', count: 20 },
  { code: 'ENG', name: 'England', count: 20 },
  { code: 'CRO', name: 'Croatia', count: 20 },
  { code: 'GHA', name: 'Ghana', count: 20 },
  { code: 'PAN', name: 'Panama', count: 20 }
];

export const TEAM_CODES = TEAMS.map(t => t.code);

export const isValidSticker = (teamCode: string, number: number) => {
  const team = TEAMS.find(t => t.code === teamCode);
  return team !== undefined && number >= 1 && number <= team.count;
};
