import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'pt' | 'en';

const TRANSLATIONS = {
  pt: {
    appTitle: 'Figurinhas 2026',
    navHome: 'Início',
    navAlbum: 'Álbum',
    navUpdate: 'Atualizar',
    navTrade: 'Trocar',
    navLists: 'Listas',
    homeProgress: 'Seu Progresso',
    homeWorldCup: 'Copa do Mundo 2026',
    homeCompleted: 'Concluído',
    homeOwned: 'Tenho',
    homeMissing: 'Faltam',
    homeDuplicates: 'Repetidas Disponíveis',
    homeReadyToTrade: 'Prontas para troca',
    homeUpdateBtn: 'Atualizar Álbum',
    onboardingTitle: 'Como você quer começar?',
    onboardingSubtitle: 'Escolha a melhor opção para o seu momento na coleção.',
    onbHave: 'Cadastrar as que já tenho',
    onbHaveDesc: 'Melhor para quem está começando agora.',
    onbMissing: 'Cadastrar as que faltam',
    onbMissingDesc: 'Melhor para quem já tem quase todas.',
    onbEmpty: 'Atualizar aos poucos',
    onbEmptyDesc: 'Começar vazio e ir adicionando.',
    updateTitle: 'Atualizar Álbum',
    updateSubtitle: 'Digite ou cole a lista de figurinhas',
    updatePlaceholder: 'Ex:\nBRA 10\nARG: 1, 2, 5',
    updatePhoto: 'Tirar Foto',
    updateText: 'Analisar Texto',
    updatePhotoAlert: 'Upload de foto em breve!',
    reviewTitle: 'Revisar Atualização',
    reviewNoValid: 'Nenhuma figurinha válida encontrada.',
    reviewDetected: 'Detectadas:',
    reviewNotOwned: 'Você ainda não tem',
    reviewOwned: 'Você já tem',
    reviewActionAdd: 'Adicionar',
    reviewActionDup: 'Somar Repetida',
    reviewInvalid: 'Inválidas/Não Reconhecidas:',
    reviewConfirm: 'Confirmar Atualização',
    reviewCancel: 'Cancelar',
    albumTitle: 'Meu Álbum',
    listsTitle: 'Listas',
    listsMissing: 'Faltantes',
    listsDuplicates: 'Repetidas',
    listsMyMissing: 'Minhas Faltantes da Copa 2026:\n\n',
    listsMyDups: 'Minhas Repetidas da Copa 2026:\n\n',
    listsCopyBtn: 'Copiar',
    listsCopied: 'Lista copiada!',
    resetConfirm: 'Tem certeza que deseja apagar todos os dados do seu álbum? Esta ação NÃO poderá ser desfeita.',
    loading: 'Carregando...',
    ocrProcessing: 'Lendo imagem... ',
    ocrError: 'Erro ao ler a imagem. Tente novamente com mais foco.',
    tradeTitle: 'Troca Rápida',
    tradeSubtitle: 'Cole as repetidas do seu amigo',
    tradePlaceholder: 'Cole a lista aqui...',
    tradeAnalyze: 'Analisar Troca',
    tradeNeed: 'Você Precisa',
    tradeHave: 'Você Já Tem',
    tradeComplete: 'Adicionar à Coleção',
    settingsTitle: 'Configurações',
    settingsData: 'Dados do Álbum',
    settingsExport: 'Exportar Backup (.json)',
    settingsExportDesc: 'Salve o seu progresso em um arquivo para não perder.',
    settingsImport: 'Importar Backup',
    settingsImportDesc: 'Restaure os dados de um arquivo .json.',
    settingsDanger: 'Zona de Perigo',
    settingsReset: 'Zerar Álbum',
    settingsResetDesc: 'Apaga todas as figurinhas permanentemente.',
    settingsImportSuccess: 'Álbum importado com sucesso!',
    settingsImportError: 'Erro ao ler arquivo inválido.',
  },
  en: {
    appTitle: 'Stickers 2026',
    navHome: 'Home',
    navAlbum: 'Album',
    navUpdate: 'Update',
    navTrade: 'Trade',
    navLists: 'Lists',
    homeProgress: 'Your Progress',
    homeWorldCup: 'World Cup 2026',
    homeCompleted: 'Completed',
    homeOwned: 'Owned',
    homeMissing: 'Missing',
    homeDuplicates: 'Available Duplicates',
    homeReadyToTrade: 'Ready to trade',
    homeUpdateBtn: 'Update Album',
    onboardingTitle: 'How do you want to start?',
    onboardingSubtitle: 'Choose the best option for your current collection.',
    onbHave: 'Enter stickers I have',
    onbHaveDesc: 'Best if you are just starting.',
    onbMissing: 'Enter missing stickers',
    onbMissingDesc: 'Best if you have almost all of them.',
    onbEmpty: 'Start empty',
    onbEmptyDesc: 'Start empty and add gradually.',
    updateTitle: 'Update Album',
    updateSubtitle: 'Type or paste your sticker list',
    updatePlaceholder: 'Ex:\nBRA 10\nARG: 1, 2, 5',
    updatePhoto: 'Take Photo',
    updateText: 'Analyze Text',
    updatePhotoAlert: 'Photo upload coming soon!',
    reviewTitle: 'Review Update',
    reviewNoValid: 'No valid stickers found.',
    reviewDetected: 'Detected:',
    reviewNotOwned: "You don't have it yet",
    reviewOwned: 'You already have it',
    reviewActionAdd: 'Add',
    reviewActionDup: 'Add Duplicate',
    reviewInvalid: 'Invalid/Unrecognized:',
    reviewConfirm: 'Confirm Update',
    reviewCancel: 'Cancel',
    albumTitle: 'My Album',
    listsTitle: 'Lists',
    listsMissing: 'Missing',
    listsDuplicates: 'Duplicates',
    listsMyMissing: 'My Missing World Cup 2026 Stickers:\n\n',
    listsMyDups: 'My World Cup 2026 Duplicates:\n\n',
    listsCopyBtn: 'Copy',
    listsCopied: 'List copied!',
    resetConfirm: 'Are you sure you want to clear all your album data? This action CANNOT be undone.',
    loading: 'Loading...',
    ocrProcessing: 'Reading image... ',
    ocrError: 'Error reading image. Try again with better focus.',
    tradeTitle: 'Fast Trade',
    tradeSubtitle: "Paste your friend's duplicates",
    tradePlaceholder: 'Paste list here...',
    tradeAnalyze: 'Analyze Trade',
    tradeNeed: 'You Need',
    tradeHave: 'You Have',
    tradeComplete: 'Add to Collection',
    settingsTitle: 'Settings',
    settingsData: 'Album Data',
    settingsExport: 'Export Backup (.json)',
    settingsExportDesc: 'Save your progress to a file.',
    settingsImport: 'Import Backup',
    settingsImportDesc: 'Restore data from a .json file.',
    settingsDanger: 'Danger Zone',
    settingsReset: 'Reset Album',
    settingsResetDesc: 'Permanently delete all your stickers.',
    settingsImportSuccess: 'Album imported successfully!',
    settingsImportError: 'Error reading invalid file.',
  }
};

interface LanguageState {
  lang: Language;
  isLoaded: boolean;
  setLoaded: (loaded: boolean) => void;
  toggleLanguage: () => void;
  t: (key: keyof typeof TRANSLATIONS.pt) => string;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      lang: 'pt',
      isLoaded: false,
      setLoaded: (loaded) => set({ isLoaded: loaded }),
      toggleLanguage: () => set((state) => ({ lang: state.lang === 'pt' ? 'en' : 'pt' })),
      t: (key) => TRANSLATIONS[get().lang][key] || key,
    }),
    {
      name: 'figurinhas_2026_lang',
      onRehydrateStorage: () => (state) => {
        state?.setLoaded(true);
      }
    }
  )
);
