import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import BottomNav from "@/components/BottomNav";
import Header from "@/components/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900 fixed inset-0 overflow-hidden`}
      >
        <div className="mx-auto max-w-md w-full h-full bg-white shadow-xl flex flex-col relative">
          <Header />
          <main className="flex-1 overflow-hidden relative">
            <div className="absolute inset-0 p-4 pb-[72px] flex flex-col overflow-hidden">
              {children}
            </div>
          </main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
